// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFUjdq9pwWTyYxspaj5Yl0zweb8sIG7Wg',
    appId: '1:111306547935:web:854b5bd04a29a339fb7f6a',
    messagingSenderId: '111306547935',
    projectId: 'social-a4a9a',
    authDomain: 'social-a4a9a.firebaseapp.com',
    storageBucket: 'social-a4a9a.appspot.com',
    measurementId: 'G-5QTRW68W1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhCuiehh92JXoQf0weg_Jtl0VQmHkSBgI',
    appId: '1:111306547935:android:c4e97c13349d7a91fb7f6a',
    messagingSenderId: '111306547935',
    projectId: 'social-a4a9a',
    storageBucket: 'social-a4a9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjKsWv4oBSrTHDk2xaTAaVTjaJrgpWL_A',
    appId: '1:111306547935:ios:9850f9e86fff0512fb7f6a',
    messagingSenderId: '111306547935',
    projectId: 'social-a4a9a',
    storageBucket: 'social-a4a9a.appspot.com',
    iosClientId: '111306547935-f7bo8vhote5mtkgo4b6bhs4fqtv53i7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialAppl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjKsWv4oBSrTHDk2xaTAaVTjaJrgpWL_A',
    appId: '1:111306547935:ios:af33115bbe19c823fb7f6a',
    messagingSenderId: '111306547935',
    projectId: 'social-a4a9a',
    storageBucket: 'social-a4a9a.appspot.com',
    iosClientId: '111306547935-mi1h23c63a3eo4k6g845opgoc306lsm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialAppl.RunnerTests',
  );
}
